/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRewardVault } from "./IRewardVault";
export type { ISavingsPool } from "./ISavingsPool";
export type { IScoreRegistry } from "./IScoreRegistry";
