/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRewardVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimPoints"
      | "getPoints"
      | "onDepositDay"
      | "points"
      | "savingsPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PointsAwarded" | "PointsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositDay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "points", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "savingsPool",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claimPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onDepositDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "points", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "savingsPool",
    data: BytesLike
  ): Result;
}

export namespace PointsAwardedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    streak: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, streak: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    streak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRewardVault extends BaseContract {
  connect(runner?: ContractRunner | null): IRewardVault;
  waitForDeployment(): Promise<this>;

  interface: IRewardVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimPoints: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoints: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  onDepositDay: TypedContractMethod<
    [user: AddressLike, streak: BigNumberish],
    [void],
    "nonpayable"
  >;

  points: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  savingsPool: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimPoints"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPoints"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "onDepositDay"
  ): TypedContractMethod<
    [user: AddressLike, streak: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "points"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "savingsPool"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PointsAwarded"
  ): TypedContractEvent<
    PointsAwardedEvent.InputTuple,
    PointsAwardedEvent.OutputTuple,
    PointsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "PointsClaimed"
  ): TypedContractEvent<
    PointsClaimedEvent.InputTuple,
    PointsClaimedEvent.OutputTuple,
    PointsClaimedEvent.OutputObject
  >;

  filters: {
    "PointsAwarded(address,uint256,uint16)": TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
    PointsAwarded: TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;

    "PointsClaimed(address,uint256)": TypedContractEvent<
      PointsClaimedEvent.InputTuple,
      PointsClaimedEvent.OutputTuple,
      PointsClaimedEvent.OutputObject
    >;
    PointsClaimed: TypedContractEvent<
      PointsClaimedEvent.InputTuple,
      PointsClaimedEvent.OutputTuple,
      PointsClaimedEvent.OutputObject
    >;
  };
}
