/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IScoreRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getUserFreq30"
      | "getUserScore"
      | "getUserStats"
      | "getUserStreak"
      | "savingsPool"
      | "score"
      | "streakDays"
      | "updateScore"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ScoreSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "getUserFreq30",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "savingsPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "score", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "streakDays",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [AddressLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserFreq30",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "savingsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "score", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "streakDays", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
}

export namespace ScoreSetEvent {
  export type InputTuple = [
    user: AddressLike,
    score: BigNumberish,
    streak: BigNumberish,
    freq30: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    score: bigint,
    streak: bigint,
    freq30: bigint
  ];
  export interface OutputObject {
    user: string;
    score: bigint;
    streak: bigint;
    freq30: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IScoreRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IScoreRegistry;
  waitForDeployment(): Promise<this>;

  interface: IScoreRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getUserFreq30: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        streak: bigint;
        freq30: bigint;
      }
    ],
    "view"
  >;

  getUserStreak: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  savingsPool: TypedContractMethod<[], [string], "view">;

  score: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  streakDays: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  updateScore: TypedContractMethod<
    [user: AddressLike, userDaysFromPool: BigNumberish[]],
    [
      [bigint, bigint, bigint] & {
        newScore: bigint;
        newStreak: bigint;
        freq30: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getUserFreq30"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        streak: bigint;
        freq30: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStreak"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "savingsPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "score"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "streakDays"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [user: AddressLike, userDaysFromPool: BigNumberish[]],
    [
      [bigint, bigint, bigint] & {
        newScore: bigint;
        newStreak: bigint;
        freq30: bigint;
      }
    ],
    "nonpayable"
  >;

  getEvent(
    key: "ScoreSet"
  ): TypedContractEvent<
    ScoreSetEvent.InputTuple,
    ScoreSetEvent.OutputTuple,
    ScoreSetEvent.OutputObject
  >;

  filters: {
    "ScoreSet(address,uint16,uint16,uint8)": TypedContractEvent<
      ScoreSetEvent.InputTuple,
      ScoreSetEvent.OutputTuple,
      ScoreSetEvent.OutputObject
    >;
    ScoreSet: TypedContractEvent<
      ScoreSetEvent.InputTuple,
      ScoreSetEvent.OutputTuple,
      ScoreSetEvent.OutputObject
    >;
  };
}
